package com.dvtrsc.valorprofs.ws.entities;
/*
 * ListResponse : response which accepts resultsets
 */
import com.dvtrsc.valorprofs.ws.entities.pojos.BaseEntity;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public abstract class ListResponse<T extends BaseEntity> extends BaseResponse
{
	private List<T> _items;
  
	public ListResponse()
	{
		this._items = new ArrayList<T>();
	}
  
	// method to implement, which will map received resultset in list. 
	public abstract T itemFromResultSet(ResultSet paramResultSet) throws SQLException;
	
	// addItems generated by prior method. Called on DBBaseController
	public void addItems(ResultSet rs) throws SQLException
	{
		if (rs != null) 
			while (rs.next()) 
				addItem(itemFromResultSet(rs));
	}
  
	public void addItem(T C)
	{
		this._items.add(C);
	}
	
	public List<T> getItems()
	{
		return this._items;
	}
}
